FREQ = 1000
SAMPLE_RATE = 16000
AMPLITUDE = 1

DURATION = 0.1
DASH_DURATION = DURATION * 3  # must be more than half of DURATION

SYM_SPACER = DURATION
LETTER_SPACER = DASH_DURATION  # must be more than half of SYM_SPACER
SPACE_DURATION = DASH_DURATION * 2.5  # must be more than half of LETTER_SPACER

GOERTZEL_SAMPLES = max(int(SYM_SPACER * 0.01 * SAMPLE_RATE), 64)
